import { Box, Divider, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Talks 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading as="h1" size="xl" textAlign="center">
          Tech talks 2023
        </Heading>
        <Divider w="sm" mx="auto" my={4} />
        <Box textAlign="center">
          <Text>Lorem Ipsum</Text>
        </Box>
      </main>
    </>
  );
}
