import Description from "@/features/Companies/components/Description";
import HomePageType from "@/features/HomePage/types/HomePageType";
import { Box, Divider, Heading } from "@chakra-ui/react";
import client from "lib/SanityClient";
import Head from "next/head";

export async function getStaticProps() {
  const pageContent = await client.fetch(`*[_type == "frontpage"][0]`);
  return {
    props: {
      pageContent,
    },
  };
}

type HomeProps = {
  pageContent: HomePageType;
};

export default function Home(props: HomeProps) {
  const { pageContent } = props;
  return (
    <>
      <Head>
        <title>Tech Talks 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading as="h1" size="xl" textAlign="center">
          {pageContent.heading}
        </Heading>
        <Divider w="sm" mx="auto" my={4} />
        <Box textAlign="center" w={["xs", "xl"]} mx="auto">
          <Description description={pageContent.description} />
        </Box>
      </main>
    </>
  );
}
